// Code generated by mockery v2.4.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/michaderbastler/pv/domain"
	mock "github.com/stretchr/testify/mock"
)

// PowerRepositoryRest is an autogenerated mock type for the PowerRepositoryRest type
type PowerRepositoryRest struct {
	mock.Mock
}

// GetPower provides a mock function with given fields: baseUrl
func (_m *PowerRepositoryRest) GetPower(baseUrl string) (domain.Power, error) {
	ret := _m.Called(baseUrl)

	var r0 domain.Power
	if rf, ok := ret.Get(0).(func(string) domain.Power); ok {
		r0 = rf(baseUrl)
	} else {
		r0 = ret.Get(0).(domain.Power)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(baseUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
