variables:
  # projectName: pv
  modulePath: '$(GOPATH)/src/github.com/$(Build.Repository.Name)' # "Build.Repository.Name" is the name of the
  # triggering repository (e.g. "michaderbastler/pv").

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: Test
    displayName: Run Tests
    jobs:
      - job: Test
        displayName: Run Tests
        steps:
          - task: GoTool@0
            displayName: 'Install Go and set GOPATH'
            inputs:
              version: '1.15.3'
              goPath: '$(HOME)/go'
          - script: |
              echo projectName
              echo $(projectName)
              echo projectName ohne Klammer
              echo $projectName
              echo System.DefaultWorkingDirectory
              echo $(System.DefaultWorkingDirectory)
              echo go version:
              go version
              echo print GOPATH:
              echo $GOPATH
              echo print GOROOT:
              echo $GOROOT
              echo print HOME:
              echo $HOME
              echo print Build.Repository.Name
              echo $(Build.Repository.Name)
              echo modulePath
              echo $(modulePath)
            displayName: print info
          - task: CopyFiles@2
            displayName: 'Copy git repo into GOPATH'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'  # "System.DefaultWorkingDirectory" is the local path
              # on the agent where the git repository gets checked out (e.g. "/home/vsts/work/1/s").
              Contents: '**'  # Copy all files of the specified source folder and its sub-folders
              TargetFolder: '$(modulePath)'