variables:
  projectName: pv

stages:
  - stage: Test
    displayName: Test source code
    jobs:
      - job: Test
        displayName: Test source code
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - script: echo $(System.DefaultWorkingDirectory)
          - script: echo $(projectName)
            displayName: print project
          - script: |
              echo go version:
              go version
              echo print GOPATH:
              echo $GOPATH
              echo print GOROOT:
              echo $GOROOT
              echo print HOME:
              echo $HOME
            displayName: print go info before
          - task: GoTool@0
            displayName: 'Install Go'
            inputs:
              version: '1.15.3'
              goPath: '$HOME/go'
          - script: |
              echo go version:
              go version
              echo print GOPATH:
              echo $GOPATH
              echo print GOROOT:
              echo $GOROOT
              echo print HOME:
              echo $HOME
            displayName: print go info after
          # Copy source code from checked out repo to GOPATH
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'  # Local path on the agent where the git repository gets checked out. For example: /home/vsts/work/1/s
              Contents: '**'  # Copy all files in the specified source folder and all files in all sub-folders
              TargetFolder: '$(GOPATH)/src/$(projectName)'
