---
apiVersion: v1
kind: Service
metadata:
  name: pv-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: pv
  ports:
  - protocol: TCP
    nodePort: 30000
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pv
  template:
    metadata:
      labels:
        app: pv
    spec:
      containers:
      - image: michaderbastler/pv:latest-linux-arm32v7
        name: pv-container
        ports:
        - containerPort: 80