---
apiVersion: v1
kind: Service
metadata:
  name: pv-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: pv
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 80
      targetPort: 80